inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - gemfiles/vendor/**/*

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/IndentHeredoc:
  EnforcedStyle: active_support

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/Debugger:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 107
  IgnoreCopDirectives: true

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y

Security/Eval:
  Exclude:
    - gemfiles/*.gemfile

#Style/AccessModifierDeclarations:
#  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
