inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/Debugger:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
