inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/IndentHeredoc:
  EnforcedStyle: active_support

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/Debugger:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 107
  IgnoreCopDirectives: true

Security/Eval:
  Exclude:
    - gemfiles/*.gemfile

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
