inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Lint/Debugger:
  Enabled: false

Metrics/ClassLength:
  Max: 101

Metrics/LineLength:
  Max: 110

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/SignalException:
  EnforcedStyle: semantic

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
