language: ruby
rvm:
  - ruby-2.4.1
  - jruby-9.1.8.0
  - ruby-2.3.4
  - ruby-2.2.7
  - ruby-head
  - jruby-head

gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head # FIXME: (uwe) Low coverage: https://github.com/jruby/jruby/issues/4404
      gemfile: gemfiles/rails50.gemfile
    - rvm: jruby-head # FIXME: (uwe) Low coverage: https://github.com/jruby/jruby/issues/4404
      gemfile: gemfiles/rails42.gemfile

before_install: gem query -i -n ^bundler$ >/dev/null || gem install bundler
