language: ruby
sudo: false
cache: bundler
rvm:
  - jruby-9.1.16.0
  - ruby-2.5.1
  - ruby-2.4.4
  - ruby-2.3.7
  - ruby-2.2.10

gemfile:
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8
