language: ruby
rvm:
  - ruby-2.4.1
  - jruby-9.1.12.0
  - ruby-2.3.4
  - ruby-2.2.7

gemfile:
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8
