dist: xenial
language: ruby
sudo: false
cache: bundler
rvm:
  - jruby-9.2.7.0
  - ruby-2.6.3
  - ruby-2.5.5
  - ruby-2.4.6
  - ruby-2.3.8
  - truffleruby-1.0.0-rc16

gemfile:
  - gemfiles/rails60.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8
