language: ruby
rvm:
  - jruby-head
  - jruby-9.0.5.0
  - jruby-9.0.4.0
  - 2.3.1
  - 2.2.5
  - 2.1.8
  - ruby-head
before_install: gem install bundler -v 1.11.2

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8
