language: ruby
sudo: false
cache: bundler
rvm:
  - jruby-9.2.0.0
  - ruby-2.5.1
  - ruby-2.4.4
  - ruby-2.3.7
  - ruby-2.2.10

gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk8

# FIXME(uwe): Remove when fixed: https://github.com/travis-ci/travis-ci/issues/9383
before_install:
  - gem install bundler
# EMXIF
