language: ruby
sudo: false
cache: bundler
rvm:
  - jruby
  - ruby-2.6
  - ruby-2.5
  - ruby-2.4
  - truffleruby

gemfile:
  - gemfiles/rails60.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  - JRUBY_OPTS="--dev --debug"

jdk:
  - oraclejdk14

matrix:
  fast_finish: true
  exclude:
    - rvm: ruby-2.4
      gemfile: gemfiles/rails60.gemfile
  allow_failures:
    - rvm: truffleruby
